service: iot-home-control

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2

plugins:
  - serverless-offline

functions:
  get-pantries:
    handler: src/lambdas/pantries/getPantries/handler.getPantries
    events:
      - http:
          path: pantries
          method: GET
  create-pantries:
    handler: src/lambdas/pantries/createPantries/handler.createPantries
    events:
      - http:
          path: pantries
          method: POST