service: iot-home-control

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2

plugins:
  - serverless-offline

functions:
  get-pantries:
    handler: dist/getPantries.getPantries
    events:
      - http:
          path: pantries
          method: GET
  get-pantries-by-id:
    handler: dist/getPantriesById.getPantriesById
    events:
      - http:
          path: pantries/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true
  get-pantries-by-user:
    handler: dist/getPantriesByUser.getPantriesByUser
    events:
      - http:
          path: pantries/user/{id}
          method: GET
  create-pantries:
    handler: dist/createPantries.createPantries
    events:
      - http:
          path: pantries
          method: POST
  update-pantries:
    handler: dist/updatePantries.updatePantries
    events:
      - http:
          path: pantries/{id}
          method: PATCH
  delete-pantries:
    handler: dist/deletePantries.deletePantries
    events:
      - http:
          path: pantries/{id}
          method: DELETE
  
  get-users:
    handler: dist/getUsers.getUsers
    events:
      - http:
          path: users
          method: GET
  get-users-by-id:
    handler: dist/getUsersById.getUsersById
    events:
      - http:
          path: users/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true
  update-users:
    handler: dist/updateUsers.updateUsers
    events:
      - http:
          path: users/{id}
          method: PATCH
  delete-users:
    handler: dist/deleteUsers.deleteUsers
    events:
      - http:
          path: users/{id}
          method: DELETE
  register:
    handler: dist/register.register
    events:
      - http:
          path: auth/register
          method: POST
    role: LambdaCognitoRole 
  login:
    handler: dist/login.login
    events:
      - http:
          path: auth/login
          method: POST
  confirm-sign-up:
    handler: dist/confirmSignUp.confirmSignUp
    events:
      - http:
          path: auth/confirm-signup
          method: POST
  edit-token-before-login:
    handler: dist/editTokenBeforeLogin.editTokenBeforeLogin
    role: EditTokenLambdaRole
  get-profile:
    handler: dist/getProfile.getProfile
    events:
      - http:
          path: users/getProfile/{cognitoUserId}
          method: GET
          

resources:
  Resources:
    EditTokenLambdaRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
                  - "cognito-idp.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "MyLambdaPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "rds-db:connect"
                    - "secretsmanager:GetSecretValue"
                  Resource: "*"  # Consider specifying resources more granularly for better security practice
                - Effect: "Allow"
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  # Replace with the specific log group ARN if needed, otherwise '*' allows all CloudWatch Logs.
                  Resource: "arn:aws:logs:us-east-2:121687014752:*"

    LambdaCognitoRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "LambdaCognitoPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "cognito-idp:AdminUpdateUserAttributes"
                    - "rds-db:connect"
                    - "secretsmanager:GetSecretValue"
                  Resource: "*"