service: iot-home-control

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2

plugins:
  - serverless-offline

functions:
  get-pantries:
    handler: dist/getPantries.getPantries
    events:
      - http:
          path: pantries
          method: GET
  get-pantries-by-id:
    handler: dist/getPantriesById.getPantriesById
    events:
      - http:
          path: pantries/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true
  create-pantries:
    handler: dist/createPantries.createPantries
    events:
      - http:
          path: pantries
          method: POST
  update-pantries:
    handler: dist/updatePantries.updatePantries
    events:
      - http:
          path: pantries/{id}
          method: PATCH
  delete-pantries:
    handler: dist/deletePantries.deletePantries
    events:
      - http:
          path: pantries/{id}
          method: DELETE
  
  get-users:
    handler: dist/getUsers.getUsers
    events:
      - http:
          path: users
          method: GET
          