service: iot-home-control

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2

plugins:
  - serverless-offline

functions:
  get-pantries:
    handler: src/lambdas/pantries/getPantries/handler.getPantries
    events:
      - http:
          path: pantries
          method: GET
  get-pantries-by-id:
    handler: src/lambdas/pantries/getPantriesById/handler.getPantriesById
    events:
      - http:
          path: pantries/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true
  create-pantries:
    handler: src/lambdas/pantries/createPantries/handler.createPantries
    events:
      - http:
          path: pantries
          method: POST
  update-pantries:
    handler: src/lambdas/pantries/updatePantries/handler.updatePantries
    events:
      - http:
          path: pantries/{id}
          method: PATCH
  delete-pantries:
    handler: src/lambdas/pantries/deletePantries/handler.deletePantries
    events:
      - http:
          path: pantries/{id}
          method: DELETE
          